
/**
 * TODO: Harshan
 * Make sure to remove the below actions on the actual development
 * SAMPLE_ADD_TEXT_SUCCESS, LOGIN_FETCH_ALL_USERS_SUCCESS, LOGIN_FETCH_ALL_USERS_FAILED
 */

export enum LoginActionTypes {
    SAMPLE_ADD_TEXT_REQUESTED = 'ADD_TEXT_REQUESTED',
    SAMPLE_ADD_TEXT_SUCCESS = 'ADD_TEXT_SUCCESS',

    LOGIN_FETCH_ALL_USERS_REQUESTED = 'LOGIN_FETCH_ALL_USERS_REQUESTED',
    LOGIN_FETCH_ALL_USERS_SUCCEEDED = 'LOGIN_FETCH_ALL_USERS_SUCCEEDED',
    LOGIN_FETCH_ALL_USERS_FAILED = 'LOGIN_FETCH_ALL_USERS_FAILED'
}