export enum ViewHistoryActionTypes {
    // SAMPLE_ADD_TEXT_REQUESTED = 'ADD_TEXT_REQUESTED',
    // SAMPLE_ADD_TEXT_SUCCESS = 'ADD_TEXT_SUCCESS',

    VIEWHISTORY_FETCH_REQUESTED = 'VIEWHISTORY_FETCH_REQUESTED',
    VIEWHISTORY_FETCH_SUCCEEDED = 'VIEWHISTORY_FETCH_SUCCEEDED',
    // VIEWHISTORY_FETCH_ALL_USERS_FAILED = 'VIEWHISTORY_FETCH_ALL_USERS_FAILED'
}